# Generated by Django 3.1.6 on 2021-02-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_iteminfo_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sate',
            new_name='state',
        ),
    ]
